site_name: "Poromics"
site_url: https://ma-sadeghi.github.io/poromics/
repo_url: https://github.com/ma-sadeghi/poromics/

theme:
  name: material
  logo: assets/logo.png
  palette:
    # Palette toggle for light mode
    - primary: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: darkblue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
  features:
    # - navigation.tabs  # Enable tabs in the navigation bar, but breaks sidebar
    - navigation.top
    - navigation.expand
    - navigation.sections
    - navigation.instant
    - content.code.copy

extra_css:
  - stylesheets/extra.css

strict: false

plugins:
  - search
  - mkdocstrings
  - mkdocs_matplotlib
  - markdown-exec
  - mkdocs-jupyter:
      theme: dark

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

docs_dir: docs

nav:
  - About: "index.md"
  - Installation: "install.md"
  - Basic usage: "usage.md"
  - API reference: "reference.md"
  - Contributing: "contributing.md"
