name: Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"

      # Setting up Julia separately is not needed, but reduces CI time due to caching
      - uses: julia-actions/setup-julia@v2
        with:
          version: "1"

      - uses: julia-actions/cache@v2
      - name: Install Dependencies
        run: make install

      - name: Build and Deploy Documentation
        run: make deploy-docs
